INSERT INTO Move(name,Type_name,power) VALUES ('Cut','Normal',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Vine Whip','Grass',45);
INSERT INTO Move(name,Type_name,power) VALUES ('Poison Sting','Poison',15);
INSERT INTO Move(name,Type_name,power) VALUES ('Thunder Shock','Electric',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Tackle','Normal',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Mud Shot','Ground',55);
INSERT INTO Move(name,Type_name,power) VALUES ('Spark','Electric',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Rock Throw','Rock',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Peck','Flying',35);
INSERT INTO Move(name,Type_name,power) VALUES ('Feint Attack','Dark',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Wing Attack','Flying',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Ice Shard','Ice',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Sludge Bomb','Poison',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Water Gun','Water',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Splash','Normal',0);
INSERT INTO Move(name,Type_name,power) VALUES ('Fire Fang','Fire',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Fury Cutter','Bug',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Bite','Dark',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Mud Slap','Ground',20);
INSERT INTO Move(name,Type_name,power) VALUES ('Zen Headbutt','Psychic',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Rock Smash','Fighting',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Confusion','Psychic',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Pound','Normal',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Poison Jab','Poison',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Sucker Punch','Dark',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Solar BeamWhip','Grass',120);
INSERT INTO Move(name,Type_name,power) VALUES ('Steel Wing','Steel',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Vine Petal Blizzard','Grass',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Karate Chop','Fighting',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Quick Attack','Normal',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Low Kick','Fighting',0);
INSERT INTO Move(name,Type_name,power) VALUES ('Shadow Claw','Ghost',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Acid','Poison',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Frost Breath','Ice',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Bug Bite','Bug',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Metal Claw','Steel',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Lick','Ghost',30);
INSERT INTO Move(name,Type_name,power) VALUES ('Bubble','Water',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Bullet Punch','Steel',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Razor Leaf','Grass',55);
INSERT INTO Move(name,Type_name,power) VALUES ('Mud Show','Ground',55);
INSERT INTO Move(name,Type_name,power) VALUES ('Scratch','Normal',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Ember','Fire',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Psycho Cut','Psychic',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Dragon Breath','Dragon',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Gunk Shot','Poison',120);
INSERT INTO Move(name,Type_name,power) VALUES ('Poison Fang','Poison',50);
INSERT INTO Move(name,Type_name,power) VALUES ('X-Scissor','Bug',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Thunder','Electric',110);
INSERT INTO Move(name,Type_name,power) VALUES ('Dark Pulse','Dark',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Psyshock','Psychic',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Rock Slide','Rock',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Hyper Beam','Normal',150);
INSERT INTO Move(name,Type_name,power) VALUES ('Dig','Ground',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Flame Charge','Fire',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Hyper Fang','Normal',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Low Sweep','Fighting',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Seed Bomb','Grass',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Sludge','Poison',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Ancient Power','Rock',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Bug Buzz','Bug',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Play Rough','Fairy',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Dragon Pulse','Dragon',85);
INSERT INTO Move(name,Type_name,power) VALUES ('Fire Blast','Fire',110);
INSERT INTO Move(name,Type_name,power) VALUES ('Bulldoze','Ground',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Magnet Bomb','Steel',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Hurricane','Flying',110);
INSERT INTO Move(name,Type_name,power) VALUES ('Dragon Claw','Dragon',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Body Slam','Normal',85);
INSERT INTO Move(name,Type_name,power) VALUES ('Ominous Wind','Ghost',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Stomp','Normal',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Signal Beam','Bug',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Earthquake','Ground',100);
INSERT INTO Move(name,Type_name,power) VALUES ('Twister','Dragon',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Drill Run','Ground',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Flamethrower','Fire',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Draining Kiss','Fairy',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Iron Head','Steel',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Psychic','Psychic',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Scald','Water',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Icy Wind','Ice',55);
INSERT INTO Move(name,Type_name,power) VALUES ('Solar Beam','Grass',120);
INSERT INTO Move(name,Type_name,power) VALUES ('Moonblast','Fairy',95);
INSERT INTO Move(name,Type_name,power) VALUES ('Petal Blizzard','Grass',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Megahorn','Bug',120);
INSERT INTO Move(name,Type_name,power) VALUES ('Swift','Normal',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Bubble Beam','Water',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Leaf Blade','Grass',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Shadow Ball','Ghost',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Night Slash','Dark',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Disarming Voice','Fairy',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Wrap','Normal',15);
INSERT INTO Move(name,Type_name,power) VALUES ('Discharge','Electric',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Dazzling Gleam','Fairy',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Brick Break','Fighting',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Air Cutter','Flying',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Hydro Pump','Water',110);
INSERT INTO Move(name,Type_name,power) VALUES ('Vice Grip','Normal',55);
INSERT INTO Move(name,Type_name,power) VALUES ('Horn Attack','Normal',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Heat Wave','Fire',95);
INSERT INTO Move(name,Type_name,power) VALUES ('Sludge Wave','Poison',95);
INSERT INTO Move(name,Type_name,power) VALUES ('Water Pulse','Water',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Drill Peck','Flying',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Stone Edge','Rock',100);
INSERT INTO Move(name,Type_name,power) VALUES ('Aerial Ace','Flying',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Thunderbolt','Electric',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Brine','Water',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Submission','Fighting',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Power Gem','Rock',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Mud Bomb','Ground',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Ice Punch','Ice',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Psybeam','Psychic',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Flame Burst','Fire',70);
INSERT INTO Move(name,Type_name,power) VALUES ('Flash Cannon','Steel',80);
INSERT INTO Move(name,Type_name,power) VALUES ('Fire Punch','Fire',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Aqua Jet','Water',40);
INSERT INTO Move(name,Type_name,power) VALUES ('Ice Beam','Ice',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Cross Chop','Fighting',100);
INSERT INTO Move(name,Type_name,power) VALUES ('Power Whip','Grass',120);
INSERT INTO Move(name,Type_name,power) VALUES ('Struggle','Normal',50);
INSERT INTO Move(name,Type_name,power) VALUES ('Blizzard','Ice',110);
INSERT INTO Move(name,Type_name,power) VALUES ('Rock Tomb','Rock',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Thunder Punch','Electric',75);
INSERT INTO Move(name,Type_name,power) VALUES ('Flame Wheel','Fire',60);
INSERT INTO Move(name,Type_name,power) VALUES ('Bone Club','Ground',65);
INSERT INTO Move(name,Type_name,power) VALUES ('Aqua Tail','Water',90);
INSERT INTO Move(name,Type_name,power) VALUES ('Cross Poison','Poison',70);
