INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,0,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,1,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,2,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,3,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,4,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,5,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,6,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,7,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,8,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,9,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,10,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,11,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,12,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,13,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,14,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,15,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,16,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,17,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,18,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (0,19,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,0,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,1,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,2,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,3,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,4,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,5,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,6,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,7,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,8,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,9,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,10,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,11,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,12,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,13,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,14,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,15,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,16,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,17,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,18,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (1,19,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,0,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,1,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,2,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,3,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,4,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,5,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,6,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,7,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,8,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,9,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,10,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,11,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,12,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,13,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,14,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,15,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,16,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,17,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,18,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (2,19,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,0,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,1,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,2,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,3,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,4,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,5,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,6,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,7,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,8,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,9,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,10,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,11,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,12,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,13,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,14,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,15,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,16,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,17,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,18,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (3,19,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,0,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,1,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,2,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,3,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,4,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,5,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,6,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,7,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,8,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,9,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,10,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,11,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,12,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,13,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,14,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,15,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,16,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,17,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,18,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (4,19,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,0,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,1,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,2,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,3,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,4,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,5,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,6,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,7,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,8,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,9,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,10,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,11,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,12,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,13,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,14,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,15,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,16,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,17,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,18,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (5,19,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,0,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,1,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,2,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,3,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,4,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,5,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,6,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,7,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,8,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,9,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,10,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,11,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,12,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,13,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,14,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,15,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,16,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,17,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,18,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (6,19,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,0,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,1,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,2,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,3,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,4,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,5,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,6,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,7,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,8,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,9,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,10,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,11,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,12,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,13,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,14,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,15,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,16,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,17,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,18,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (7,19,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,0,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,1,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,2,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,3,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,4,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,5,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,6,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,7,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,8,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,9,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,10,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,11,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,12,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,13,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,14,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,15,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,16,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,17,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,18,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (8,19,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,0,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,1,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,2,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,3,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,4,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,5,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,6,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,7,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,8,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,9,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,10,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,11,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,12,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,13,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,14,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,15,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,16,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,17,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,18,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (9,19,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,0,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,1,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,2,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,3,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,4,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,5,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,6,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,7,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,8,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,9,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,10,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,11,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,12,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,13,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,14,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,15,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,16,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,17,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,18,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (10,19,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,0,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,1,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,2,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,3,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,4,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,5,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,6,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,7,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,8,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,9,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,10,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,11,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,12,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,13,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,14,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,15,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,16,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,17,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,18,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (11,19,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,0,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,1,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,2,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,3,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,4,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,5,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,6,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,7,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,8,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,9,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,10,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,11,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,12,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,13,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,14,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,15,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,16,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,17,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,18,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (12,19,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,0,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,1,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,2,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,3,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,4,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,5,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,6,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,7,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,8,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,9,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,10,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,11,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,12,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,13,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,14,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,15,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,16,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,17,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,18,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (13,19,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,0,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,1,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,2,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,3,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,4,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,5,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,6,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,7,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,8,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,9,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,10,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,11,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,12,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,13,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,14,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,15,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,16,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,17,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,18,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (14,19,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,0,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,1,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,2,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,3,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,4,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,5,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,6,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,7,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,8,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,9,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,10,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,11,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,12,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,13,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,14,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,15,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,16,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,17,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,18,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (15,19,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,0,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,1,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,2,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,3,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,4,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,5,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,6,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,7,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,8,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,9,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,10,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,11,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,12,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,13,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,14,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,15,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,16,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,17,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,18,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (16,19,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,0,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,1,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,2,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,3,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,4,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,5,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,6,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,7,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,8,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,9,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,10,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,11,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,12,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,13,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,14,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,15,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,16,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,17,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,18,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (17,19,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,0,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,1,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,2,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,3,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,4,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,5,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,6,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,7,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,8,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,9,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,10,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,11,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,12,'Temprerate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,13,'Temperate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,14,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,15,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,16,'Swamp');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,17,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,18,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (18,19,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,0,'Arctic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,1,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,2,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,3,'Desert');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,4,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,5,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,6,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,7,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,8,'Taiga');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,9,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,10,'Tropical Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,11,'Oceanic');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,12,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,13,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,14,'Grassland');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,15,'Mountain');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,16,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,17,'Tundra');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,18,'Tempreate Rain Forest');
INSERT INTO Biome_Location(Latitude,Longitude,Biome_name) VALUES (19,19,'Arctic');
