INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Taiga','Bug');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tropical Rain Forest','Bug');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tempreate Rain Forest','Bug');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Dragon');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tundra','Dragon');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tundra','Ice');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Arctic','Ice');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Fighting');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Fire');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Taiga','Fire');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Flying');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Temperate Rain Forest','Flying');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Swamp','Flying');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Oceanic','Flying');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Grassland','Grass');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Taiga','Grass');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tundra','Ghost');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Arctic','Ghost');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Ground');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Grassland','Ground');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Ground');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Electric');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tropical Rain Forest','Electric');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tundra','Normal');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Temprerate Rain Forest','Normal');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Grassland','Normal');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Normal');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Oceanic','Normal');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tropical Rain Forest','Poison');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Swamp','Poison');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Poison');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Psychic');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Swamp','Psychic');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Rock');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Grassland','Rock');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Desert','Rock');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Oceanic','Water');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Swamp','Water');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Steel');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Tundra','Steel');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Taiga','Steel');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Temperate Rain Forest','Fairy');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Taiga','Fairy');
INSERT INTO Type_Biome(Biome_name,Type_name) VALUES ('Mountain','Fairy');
