CREATE TABLE Type (
name 			CHAR(10),
PRIMARY KEY (name));

             /* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Bug');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Dragon');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Ice');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Fighting');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Fire');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Flying');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Grass');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Ghost');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Ground');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Electric');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Normal');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Poison');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Psychic');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Rock');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Water');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Steel');
/* INSERT QUERY */
INSERT INTO TABLE_NAME(Type) 
VALUES 
  ('Fairy');
