INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Bulbasaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vine Whip','Bulbasaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Bulbasaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Bulbasaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Bulbasaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Ivysaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vine Whip','Ivysaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Ivysaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Ivysaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Ivysaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vine Petal Blizzard','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar BeamWhip','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Petal Blizzard','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Venusaur');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Charmander');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Charmander');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Burst','Charmander');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Charge','Charmander');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Charmander');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Charmeleon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Charmeleon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Punch','Charmeleon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Burst','Charmeleon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Charmeleon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Charizard');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wing Attack','Charizard');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Claw','Charizard');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Charizard');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Charizard');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Squirtle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Squirtle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Squirtle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Squirtle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Squirtle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Wartortle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Wartortle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Wartortle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Wartortle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Wartortle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Blastoise');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Blastoise');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flash Cannon','Blastoise');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Blastoise');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Blastoise');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Caterpie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Caterpie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Caterpie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Metapod');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Metapod');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Metapod');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Butterfree');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Butterfree');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Butterfree');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Buzz','Butterfree');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Signal Beam','Butterfree');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Weedle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Weedle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Weedle');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Kakuna');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Kakuna');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Kakuna');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Beedrill');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Beedrill');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Beedrill');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Beedrill');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Beedrill');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Pidgey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Pidgey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Twister','Pidgey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Pidgey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Pidgey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wing Attack','Pidgeotto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Pidgeotto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Twister','Pidgeotto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Pidgeotto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Pidgeotto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wing Attack','Pidgeot');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Pidgeot');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hurricane','Pidgeot');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Pidgeot');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Pidgeot');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Rattata');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Rattata');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Rattata');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Fang','Rattata');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Rattata');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Raticate');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Raticate');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Raticate');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Fang','Raticate');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Raticate');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Spearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Spearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Spearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Fang','Spearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Spearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Fearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Fearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Fearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Twister','Fearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Drill Run','Fearow');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Ekans');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Ekans');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Gunk Shot','Ekans');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Ekans');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wrap','Ekans');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Arbok');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Arbok');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Gunk Shot','Arbok');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Arbok');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Arbok');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Pikachu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Pikachu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Pikachu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Pikachu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder','Pikachu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Raichu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Spark','Raichu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Raichu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Punch','Raichu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder','Raichu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Sandshrew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Show','Sandshrew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Sandshrew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Slide','Sandshrew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Sandshrew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Metal Claw','Sandslash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Sandslash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Sandslash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bulldoze','Sandslash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Sandslash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Nidoran-f');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Nidoran-f');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Nidoran-f');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Nidoran-f');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Nidoran-f');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Nidorina');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Nidorina');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Nidorina');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Nidorina');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Nidorina');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Nidoqueen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Nidoqueen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Nidoqueen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Nidoqueen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Nidoqueen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Nidoran-m');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Nidoran-m');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Horn Attack','Nidoran-m');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Nidoran-m');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Nidoran-m');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Nidorino');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Nidorino');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Horn Attack','Nidorino');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Nidorino');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Nidorino');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Nidoking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Nidoking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Megahorn','Nidoking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Nidoking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Nidoking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Clefairy');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Clefairy');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Clefairy');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Disarming Voice','Clefairy');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Clefairy');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Clefable');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Clefable');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Clefable');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dazzling Gleam','Clefable');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Clefable');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Vulpix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Vulpix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Heat Wave','Vulpix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Vulpix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Vulpix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Feint Attack','Ninetales');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Ninetales');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Heat Wave','Ninetales');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Ninetales');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Ninetales');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Feint Attack','Jigglypuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Jigglypuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Disarming Voice','Jigglypuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Jigglypuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Play Rough','Jigglypuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Feint Attack','Wigglytuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Wigglytuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dazzling Gleam','Wigglytuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Wigglytuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Play Rough','Wigglytuff');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Zubat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Zubat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Zubat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Zubat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Zubat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Golbat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wing Attack','Golbat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ominous Wind','Golbat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Golbat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Golbat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Oddish');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Oddish');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Oddish');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Oddish');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Oddish');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Gloom');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Gloom');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Gloom');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Petal Blizzard','Gloom');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Gloom');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Vileplume');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Vileplume');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Vileplume');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Petal Blizzard','Vileplume');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Vileplume');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Paras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Paras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Paras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Paras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Poison','Paras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Parasect');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wing Attack','Parasect');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Parasect');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Parasect');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Poison','Parasect');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Venonat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Venonat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Signal Beam','Venonat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Venonat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Venonat');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Venomoth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Bite','Venomoth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug buzz','Venomoth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Fang','Venomoth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Venomoth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Diglett');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Diglett');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Diglett');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Diglett');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Bomb','Diglett');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sucker Punch','Dugtrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Dugtrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Dugtrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Dugtrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Bomb','Dugtrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Meowth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Meowth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Meowth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Night Slash','Meowth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Meowth');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Persian');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Feint Attack','Persian');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Play Rough','Persian');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Gem','Persian');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Night Slash','Persian');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Psyduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Psyduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Psyduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Psyduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Psyduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Golduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Golduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Golduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Golduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro pump','Golduck');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Mankey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Mankey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Mankey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Mankey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Sweep','Mankey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Primeape');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Primeape');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Night Slash','Primeape');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Primeape');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Sweep','Primeape');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Growlithe');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Growlithe');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Wheel','Growlithe');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Growlithe');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Growlithe');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Arcanine');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Fang','Arcanine');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Arcanine');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bulldoze','Arcanine');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Arcanine');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Poliwag');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Poliwag');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Poliwag');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Poliwag');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Bomb','Poliwag');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Poliwhirl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Poliwhirl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scald','Poliwhirl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Poliwhirl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Bomb','Poliwhirl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Poliwrath');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Poliwrath');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Punch','Poliwrath');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Submission','Poliwrath');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Poliwrath');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Abra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Abra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Signal Beam','Abra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psyshock','Abra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Kadabra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psycho Cut','Kadabra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Kadabra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dazzling Gleam','Kadabra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Kadabra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Alakazam');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psycho Cut','Alakazam');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Alakazam');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dazzling Gleam','Alakazam');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Alakazam');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Machop');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Machop');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Machop');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Machop');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Sweep','Machop');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Machoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Machoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Machoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Machoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Submission','Machoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bullet Punch','Machamp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Machamp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Machamp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cross Chop','Machamp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Submission','Machamp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Bellsprout');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vine Whip','Bellsprout');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Bellsprout');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Bellsprout');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wrap','Bellsprout');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Weepinbell');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Weepinbell');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Weepinbell');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Weepinbell');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Weepinbell');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Victreebel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Razor Leaf','Victreebel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Victreebel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Leaf Blade','Victreebel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Victreebel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Tentacool');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Sting','Tentacool');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Tentacool');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Tentacool');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wrap','Tentacool');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Tentacruel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Tentacruel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Blizzard','Tentacruel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Tentacruel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Tentacruel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Geodude');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Throw','Geodude');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Slide','Geodude');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Geodude');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Geodude');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Graveler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Throw','Graveler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Slide','Graveler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Graveler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Graveler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Golem');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Throw','Golem');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Golem');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Golem');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Golem');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Ponyta');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Ponyta');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Wheel','Ponyta');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Ponyta');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flame Charge','Ponyta');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Rapidash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Rapidash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Heat Wave','Rapidash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Rapidash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Drill Run','Rapidash');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Slowpoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Slowpoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Slowpoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Slowpoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psyshock','Slowpoke');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Slowbro');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Slowbro');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Slowbro');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Slowbro');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Slowbro');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Spark','Magnemite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Magnemite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Magnet Bomb','Magnemite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Magnemite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Magnemite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Spark','Magneton');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Magneton');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Magnet Bomb','Magneton');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Magneton');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flash Cannon','Magneton');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Farfetch''d');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Cut','Farfetch''d');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Air Cutter','Farfetch''d');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Farfetch''d');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Leaf Blade','Farfetch''d');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Doduo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Doduo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Swift','Doduo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Doduo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Drill Peck','Doduo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Dodrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Feint Attack','Dodrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Drill Peck','Dodrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aerial Ace','Dodrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Dodrio');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Seel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Shard','Seel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Seel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Seel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Seel');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Frost Breath','Dewgong');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Shard','Dewgong');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Dewgong');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Dewgong');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Blizzard','Dewgong');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Grimer');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Grimer');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge','Grimer');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Grimer');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Bomb','Grimer');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Muk');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Muk');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Muk');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Muk');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Muk');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Shellder');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Shard','Shellder');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Shellder');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Shellder');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Shellder');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Frost Breath','Cloyster');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Shard','Cloyster');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Cloyster');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Cloyster');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Cloyster');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Lick','Gastly');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sucker Punch','Gastly');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Gastly');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Gastly');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ominous Wind','Gastly');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Lick','Haunter');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sucker Punch','Haunter');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Haunter');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Haunter');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Haunter');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Claw','Gengar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sucker Punch','Gengar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Gengar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Wave','Gengar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Gengar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Onix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Throw','Onix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Slide','Onix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Onix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Iron Head','Onix');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Drowzee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Drowzee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Drowzee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psyshock','Drowzee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Drowzee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Hypno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Hypno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Hypno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psyshock','Hypno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Hypno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Krabby');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Krabby');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vice Grip','Krabby');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Krabby');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Krabby');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Metal Claw','Kingler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Kingler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vice Grip','Kingler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Kingler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Kingler');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Voltorb');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Spark','Voltorb');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Voltorb');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Voltorb');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Signal Beam','Voltorb');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Electrode');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Spark','Electrode');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Electrode');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Electrode');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Electrode');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Exeggcute');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Exeggcute');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Exeggcute');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Exeggcute');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Exeggutor');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Exeggutor');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Exeggutor');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Seed Bomb','Exeggutor');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Exeggutor');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Cubone');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Cubone');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bone Club','Cubone');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Cubone');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bulldoze','Cubone');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Marowak');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Marowak');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bone Club','Marowak');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Marowak');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Marowak');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Hitmonlee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Hitmonlee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Sweep','Hitmonlee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Hitmonlee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stomp','Hitmonlee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bullet Punch','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Punch','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Punch','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Punch','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Hitmonchan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Lick','Lickitung');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Lickitung');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stomp','Lickitung');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Lickitung');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Lickitung');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Koffing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Koffing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Koffing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge','Koffing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Koffing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Weezing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Acid','Weezing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dark Pulse','Weezing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Weezing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Weezing');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Rhyhorn');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Rhyhorn');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stomp','Rhyhorn');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bulldoze','Rhyhorn');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Horn Attack','Rhyhorn');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Rhydon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Rhydon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Rhydon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Rhydon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Megahorn','Rhydon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Chansey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Chansey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dazzling Gleam','Chansey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Chansey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Chansey');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vine Whip','Tangela');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Sludge Bomb','Tangela');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Tangela');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Whip','Tangela');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Kangaskhan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Slap','Kangaskhan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Kangaskhan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brick Break','Kangaskhan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stomp','Kangaskhan');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Horsea');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble','Horsea');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Horsea');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Horsea');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flash Cannon','Horsea');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Seadra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Breath','Seadra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Seadra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Blizzard','Seadra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Seadra');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Goldeen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Goldeen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Goldeen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Horn Attack','Goldeen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Goldeen');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Poison Jab','Seaking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Peck','Seaking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Drill Run','Seaking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Megahorn','Seaking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Seaking');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Staryu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Staryu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bubble Beam','Staryu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Gem','Staryu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Swift','Staryu');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Starmie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Starmie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Starmie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Power Gem','Starmie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Starmie');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Mr. Mime');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Mr. Mime');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Mr. Mime');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Mr. Mime');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Mr. Mime');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Scyther');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Scyther');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bug Buzz','Scyther');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Scyther');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Night Slash','Scyther');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Jynx');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Frost Breath','Jynx');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psyshock','Jynx');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Punch','Jynx');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Draining Kiss','Jynx');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Low Kick','Electabuzz');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Electabuzz');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Electabuzz');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder','Electabuzz');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Punch','Electabuzz');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Magmar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Karate Chop','Magmar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Magmar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Magmar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Punch','Magmar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Pinsir');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Smash','Pinsir');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Submission','Pinsir');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Vice Grip','Pinsir');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('X-Scissor','Pinsir');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Tauros');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Tauros');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Tauros');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Iron Head','Tauros');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Horn Attack','Tauros');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Splash','Magikarp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Magikarp');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Gyarados');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Breath','Gyarados');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Twister','Gyarados');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Gyarados');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Gyarados');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Frost Breath','Lapras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Shard','Lapras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Blizzard','Lapras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Lapras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Lapras');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Ditto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Struggle','Ditto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Eevee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Eevee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Eevee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dig','Eevee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Swift','Eevee');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Vaporeon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Vaporeon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Vaporeon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Vaporeon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Jolteon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Jolteon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Jolteon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder','Jolteon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Flareon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Flareon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Flareon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Heat Wave','Flareon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Tackle','Porygon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Quick Attack','Porygon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Porygon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psybeam','Porygon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Signal Beam','Porygon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Omanyte');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Omanyte');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Omanyte');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Brine','Omanyte');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Omanyte');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Gun','Omastar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Throw','Omastar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Omastar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hydro Pump','Omastar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Slide','Omastar');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Scratch','Kabuto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Kabuto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Jet','Kabuto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Kabuto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Rock Tomb','Kabuto');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fury Cutter','Kabutops');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Mud Shot','Kabutops');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Kabutops');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Water Pulse','Kabutops');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Stone Edge','Kabutops');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Bite','Aerodactyl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Aerodactyl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ancient Power','Aerodactyl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Iron Head','Aerodactyl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Aerodactyl');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Lick','Snorlax');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Zen Headbutt','Snorlax');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Body Slam','Snorlax');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Snorlax');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Snorlax');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Frost Breath','Articuno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Blizzard','Articuno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ice Beam','Articuno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Icy Wind','Articuno');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder Shock','Zapdos');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Discharge','Zapdos');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunderbolt','Zapdos');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Thunder','Zapdos');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Ember','Moltres');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Flamethrower','Moltres');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Moltres');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Heat Wave','Moltres');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Breath','Dragon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Dragon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Twister','Dragon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wrap','Dragon');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Breath','Dragonair');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Aqua Tail','Dragonair');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Dragonair');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Wrap','Dragonair');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Breath','Dragonite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Steel Wing','Dragonite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Claw','Dragonite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Dragonite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Dragonite');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Confusion','Mewtwo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psycho Cut','Mewtwo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Mewtwo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Mewtwo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Shadow Ball','Mewtwo');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Pound','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Dragon Pulse','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Earthquake','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Fire Blast','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hyper Beam','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Hurricane','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Moonblast','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Psychic','Mew');
INSERT INTO Move_Species(Move_name,Species_name) VALUES ('Solar Beam','Mew');
